const Ciudades: { [key: string]: string[] } = {
    ASUNCIÓN: ["ASUNCIÓN"],
    CONCEPCIÓN: [
      "CONCEPCIÓN",
      "BELÉN",
      "HORQUETA",
      "LORETO",
      "SAN CARLOS DEL APA",
      "SAN LÁZARO",
      "YBY YAÚ",
      "AZOTE'Y",
      "SARGENTO JOSÉ FÉLIX LÓPEZ",
      "SAN ALFREDO",
      "PASO BARRETO",
    ],
    "SAN PEDRO": [
      "SAN PEDRO DEL YCUAMANDYYÚ",
      "ANTEQUERA",
      "CHORÉ",
      "GENERAL ELIZARDO AQUINO",
      "ITACURUBÍ DEL ROSARIO",
      "LIMA",
      "NUEVA GERMANIA",
      "SAN ESTANISLAO",
      "SAN PABLO",
      "TACUATÍ",
      "UNIÓN",
      "25 DE DICIEMBRE",
      "VILLA DEL ROSARIO",
      "GENERAL FRANCISCO ISIDORO RESQUÍN",
      "YATAITY DEL NORTE",
      "GUAJAYVI",
      "CAPIIBARY",
      "SANTA ROSA DEL AGUARAY",
      "YRYBUCUA",
      "LIBERACIÓN",
    ],
    CORDILLERA: [
      "CAACUPÉ",
      "ALTOS",
      "ARROYOS Y ESTEROS",
      "ATYRÁ",
      "CARAGUATAY",
      "EMBOSCADA",
      "EUSEBIO AYALA",
      "ISLA PUCÚ",
      "ITACURUBÍ DE LA CORDILLERA",
      "JUAN DE MENA",
      "LOMA GRANDE",
      "MBOCAYATY DEL YHAGUY",
      "NUEVA COLOMBIA",
      "PIRIBEBUY",
      "PRIMERO DE MARZO",
      "SAN BERNARDINO",
      "SANTA ELENA",
      "TOBATÍ",
      "VALENZUELA",
      "SAN JOSE OBRERO",
    ],
    GUAIRÁ: [
      "VILLARRICA",
      "BORJA",
      "CAPITÁN MAURICIO JOSÉ TROCHE",
      "CORONEL MARTÍNEZ",
      "FÉLIX PÉREZ CARDOZO",
      "GRAL. EUGENIO A. GARAY",
      "INDEPENDENCIA",
      "ITAPÉ",
      "ITURBE",
      "JOSÉ FASSARDI",
      "MBOCAYATY",
      "NATALICIO TALAVERA",
      "ÑUMÍ",
      "SAN SALVADOR",
      "YATAITY",
      "DOCTOR BOTTRELL",
      "PASO YOBAI",
      "TEBICUARY",
    ],
    CAAGUAZÚ: [
      "CORONEL OVIEDO",
      "CAAGUAZÚ",
      "CARAYAÓ",
      "DR. CECILIO BÁEZ",
      "SANTA ROSA DEL MBUTUY",
      "DR. JUAN MANUEL FRUTOS",
      "REPATRIACIÓN",
      "NUEVA LONDRES",
      "SAN JOAQUÍN",
      "SAN JOSÉ DE LOS ARROYOS",
      "YHÚ",
      "DR. J. EULOGIO ESTIGARRIBIA",
      "R.I. 3 CORRALES",
      "RAÚL ARSENIO OVIEDO",
      "JOSÉ DOMINGO OCAMPOS",
      "MARISCAL FRANCISCO SOLANO LÓPEZ",
      "LA PASTORA",
      "3 DE FEBRERO",
      "SIMÓN BOLIVAR",
      "VAQUERÍA",
      "TEMBIAPORÁ",
      "NUEVA TOLEDO",
    ],
    CAAZAPÁ: [
      "CAAZAPÁ",
      "ABAÍ",
      "BUENA VISTA",
      "DR. MOISÉS S. BERTONI",
      "GRAL. HIGINIO MORINIGO",
      "MACIEL",
      "SAN JUAN NEPOMUCENO",
      "TAVAÍ",
      "YEGROS",
      "YUTY",
      "3 DE MAYO",
    ],
    ITAPÚA: [
      "ENCARNACIÓN",
      "BELLA VISTA",
      "CAMBYRETÁ",
      "CAPITÁN MEZA",
      "CAPITÁN MIRANDA",
      "NUEVA ALBORADA",
      "CARMEN DEL PARANÁ",
      "CORONEL BOGADO",
      "CARLOS ANTONIO LÓPEZ",
      "NATALIO",
      "FRAM",
      "GENERAL ARTIGAS",
      "GENERAL DELGADO",
      "HOHENAU",
      "JESÚS",
      "JOSÉ LEANDRO OVIEDO",
      "OBLIGADO",
      "MAYOR JULIO DIONISIO OTAÑO",
      "SAN COSME Y DAMIAN",
      "SAN PEDRO DEL PARANÁ",
      "SAN RAFAEL DEL PARANÁ",
      "TRINIDAD",
      "EDELIRA",
      "TOMÁS ROMERO PEREIRA",
      "ALTO VERÁ",
      "LA PAZ",
      "YATYTAY",
      "SAN JUAN DEL PARANÁ",
      "PIRAPÓ",
      "ITAPÚA POTY",
    ],
    MISIONES: [
      "SAN JUAN BAUTISTA DE LAS MISIONES",
      "AYOLAS",
      "SAN IGNACIO",
      "SAN MIGUEL",
      "SAN PATRICIO",
      "SANTA MARÍA",
      "SANTA ROSA",
      "SANTIAGO",
      "VILLA FLORIDA",
      "YABEBYRY",
    ],
    PARAGUARI: [
      "PARAGUARÍ",
      "ACAHAY",
      "CAAPUCÚ",
      "CABALLERO",
      "CARAPEGUÁ",
      "ESCOBAR",
      "LA COLMENA",
      "MBUYAPEY",
      "PIRAYÚ",
      "QUIINDY",
      "QUYQUYHÓ",
      "ROQUE GONZALEZ DE SANTACRUZ",
      "SAPUCÁI",
      "TEBICUARY-MÍ",
      "YAGUARÓN",
      "YBYCUÍ",
      "YBYTYMÍ",
    ],
    "ALTO PARANÁ": [
      "CIUDAD DEL ESTE",
      "PRESIDENTE FRANCO",
      "DOMINGO MARTÍNEZ DE IRALA",
      "DR. JUAN LEÓN MALLORQUÍN",
      "HERNANDARIAS",
      "ITAKYRY",
      "JUAN E. O'LEARY",
      "ÑACUNDAY",
      "YGUAZÚ",
      "LOS CEDRALES",
      "MINGA GUAZÚ",
      "SAN CRISTOBAL",
      "SANTA RITA",
      "NARANJAL",
      "SANTA ROSA DEL MONDAY",
      "MINGA PORÁ",
      "MBARACAYÚ",
      "SAN ALBERTO",
      "IRUÑA",
      "SANTA FE DEL PARANÁ",
      "TAVAPY",
      "DR. RAÚL PEÑA",
    ],
    CENTRAL: [
      "AREGUÁ",
      "CAPIATÁ",
      "FERNANDO DE LA MORA",
      "GUARAMBARÉ",
      "ITÁ",
      "ITAUGUÁ",
      "LAMBARÉ",
      "LIMPIO",
      "LUQUE",
      "MARIANO ROQUE ALONSO",
      "NUEVA ITALIA",
      "ÑEMBY",
      "SAN ANTONIO",
      "SAN LORENZO",
      "VILLA ELISA",
      "VILLETA",
      "YPACARAÍ",
      "YPANÉ",
      "J. AUGUSTO SALDIVAR",
    ],
    ÑEEMBUCÚ: [
      "PILAR",
      "ALBERDI",
      "CERRITO",
      "DESMOCHADOS",
      "GRAL. JOSÉ EDUVIGIS DÍAZ",
      "GUAZÚ-CUÁ",
      "HUMAITÁ",
      "ISLA UMBÚ",
      "LAURELES",
      "MAYOR JOSÉ DEJESÚS MARTÍNEZ",
      "PASO DE PATRIA",
      "SAN JUAN BAUTISTA DE ÑEEMBUCÚ",
      "TACUARAS",
      "VILLA FRANCA",
      "VILLA OLIVA",
      "VILLALBÍN",
    ],
    AMAMBAY: [
      "PEDRO JUAN CABALLERO",
      "BELLA VISTA",
      "CAPITÁN BADO",
      "ZANJA PYTÃ",
      "KARAPAÍ",
    ],
    CANINDEYÚ: [
      "SALTO DEL GUAIRÁ",
      "CORPUS CHRISTI",
      "VILLA CURUGUATY",
      "VILLA YGATIMÍ",
      "ITANARÁ",
      "YPEJHÚ",
      "FRANCISCO CABALLERO ALVAREZ",
      "KATUETÉ",
      "LA PALOMA DEL ESPÍRITU SANTO",
      "NUEVA ESPERANZA",
      "YASY CAÑY",
      "YBYRAROBANÁ",
      "YBY PYTÁ",
    ],
    "PRESIDENTE HAYES": [
      "BENJAMÍN ACEVAL",
      "PUERTO PINASCO",
      "VILLA HAYES",
      "NANAWA",
      "JOSÉ FALCÓN",
      "TTE. 1° MANUEL IRALA FERNÁNDEZ",
      "TENIENTE ESTEBAN MARTÍNEZ",
      "GENERAL JOSÉ MARÍA BRUGUEZ",
    ],
    BOQUERÓN: ["MARISCAL JOSÉ FÉLIX ESTIGARRIBIA", "FILADELFIA", "LOMA PLATA"],
    "ALTO PARAGUAY": [
      "FUERTE OLIMPO",
      "PUERTO CASADO",
      "BAHÍA NEGRA",
      "CARMELO PERALTA",
    ],
  };
  export default Ciudades;
  